/**
 * Shared helpers for the four compliance reporters (T-23..T-26).
 *
 * Each reporter consumes the IR + scanner Finding[] and produces a
 * human-readable text report tailored to one regulation. The shape of
 * each report differs — Japanese incident-style for 改正個情法, English
 * checklists for NTIA / EU CRA, validator tables for METI — but the
 * common scaffolding lives here:
 *
 *   - The snippet registry (maps a snippet id to its {title, version,
 *     citation, retrievalDate} record loaded from the
 *     `regulation-snippets/` modules)
 *   - The snippet-age check (AC-003-5 — warn when any vendored snippet
 *     is more than 12 months past its `retrievalDate`)
 *   - The shared citation-footer formatter that every report appends
 *     verbatim
 *
 * Per ADR-0006 §Decision: Layer 4 (Emitters) sub-module. Reads only the
 * IR (Layer 2), the scanner Finding type (Layer 3), and its own snippet
 * sub-modules. No parser / CLI imports.
 *
 * Spec mapping: AC-003-5, AC-003-7, AC-003-8, ADR-0005, ADR-0006.
 */
import { APPI_26_2_SNIPPET } from './regulation-snippets/appi-26-2.js';
import { METI_SBOM_V2_SNIPPET } from './regulation-snippets/meti-sbom-v2.js';
import { NTIA_SNIPPET } from './regulation-snippets/ntia.js';
import { EU_CRA_SNIPPET } from './regulation-snippets/eu-cra.js';

export type RegulationId = 'appi-26-2' | 'meti-sbom-v2' | 'ntia' | 'eu-cra';

export interface RegulationSnippet {
  id: RegulationId;
  title: string;
  version: string;
  retrievalDate: string;
  citation: string;
}

export const REGULATION_SNIPPETS: Readonly<
  Record<RegulationId, RegulationSnippet>
> = {
  'appi-26-2': APPI_26_2_SNIPPET,
  'meti-sbom-v2': METI_SBOM_V2_SNIPPET,
  ntia: NTIA_SNIPPET,
  'eu-cra': EU_CRA_SNIPPET,
};

/**
 * Default snippet-staleness threshold in months. AC-003-5 mandates a
 * warning when a vendored snippet is more than 12 months past its
 * `retrievalDate`; the default matches.
 */
export const DEFAULT_SNIPPET_MAX_AGE_MONTHS = 12;

/**
 * Decide whether a snippet's retrievalDate is more than
 * `maxAgeMonths` past `now`. Returns true on unparseable dates so a
 * malformed snippet does not silently slip through; the AC-003-5
 * warning is the user-facing surface in either case.
 */
export function isSnippetStale(
  snippet: RegulationSnippet,
  maxAgeMonths: number = DEFAULT_SNIPPET_MAX_AGE_MONTHS,
  now: Date = new Date(),
): boolean {
  const retrieved = Date.parse(snippet.retrievalDate);
  if (Number.isNaN(retrieved)) return true;
  const ageMs = now.getTime() - retrieved;
  const monthMs = 30.44 * 24 * 60 * 60 * 1000; // average month length
  const maxMs = maxAgeMonths * monthMs;
  return ageMs > maxMs;
}

/**
 * Return one-line warnings for every stale snippet, or an empty array
 * when all snippets are within `maxAgeMonths`. CLI / report header
 * emits these as preamble lines.
 */
export function listStaleSnippetWarnings(
  maxAgeMonths: number = DEFAULT_SNIPPET_MAX_AGE_MONTHS,
  now: Date = new Date(),
): string[] {
  const warnings: string[] = [];
  for (const snippet of Object.values(REGULATION_SNIPPETS)) {
    if (isSnippetStale(snippet, maxAgeMonths, now)) {
      warnings.push(
        `warning: regulation snippet ${snippet.id} retrieved ${snippet.retrievalDate} (older than ${maxAgeMonths} months). Refresh against the upstream source.`,
      );
    }
  }
  return warnings;
}

/**
 * Format a single-line citation footer for a regulation report.
 * Includes the regulation title, retrieval date, and tool tag. Every
 * compliance reporter appends this verbatim as the document's final
 * line; CLI tests assert presence of the tool tag and retrieval date.
 */
export function formatComplianceFooter(
  regulationId: RegulationId,
  creatorVersion: string,
): string {
  const snippet = REGULATION_SNIPPETS[regulationId];
  return `${snippet.citation} — generated by sbom-pilot-${creatorVersion} on ${snippet.retrievalDate}`;
}
